### ISSUE TITLE
error in cmd in README.md

### ISSUE THREAD

**Issue by eagle840** [CloudNativeTech/gdg-terraform-gcp-workshop#1]
While running through the commands in README.md, 
Under: How to install Google Cloud SDK?  step1
getting error when running in ubuntu
export $GCLOUD_PATH=$HOME
bash: export: `/home/nicholas=/home/nicholas': not a valid identifier

The fix is:
export GCLOUD_PATH=$HOME

**Comment by pradeepbhadani** [comment]
Thanks @eagle840 . I have updated README.md
